services:
  google-contacts-birthday-ical-calendar-dev:
    container_name: google-contacts-birthday-ical-calendar-dev
    build:
      context: .
      target: base
    working_dir: /app
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - type: bind
        source: ./
        target: /app
