name: Test
'on':
  - push
  - pull_request
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@v2
        run: ec

      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Run yamllint
        run: |
          yamllint --strict --config-file .yamllint .

      - name: Run tests
        run: |
          docker-compose -f docker-compose.test.yml build
